### ISSUE TITLE
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by xxx2974** [levyfan/reid-mgn#8]
how can I solve the problem?????

(pytorch-mgn) [xxx@localhost reid-mgn]$ python mgn/mgn.py
cuda

Namespace(model='mgn', root='/home/xiaozhenzhen/data/reid-mgn/mgn/../Market-1501-v15.09.15', workers=28.0)

Traceback (most recent call last):
  File "mgn/mgn.py", line 313, in <module>
    run()
  File "mgn/mgn.py", line 257, in run
    mgn = MGN(num_classes=len(train_dataset.unique_ids)).to(DEVICE)
  File "mgn/mgn.py", line 115, in __init__
    self.fc_id_2048_0 = nn.Linear(2048, num_classes)
  File "/home/xiaozhenzhen/anaconda2/envs/pytorch-mgn/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 46, in __init__
    self.reset_parameters()
  File "/home/xiaozhenzhen/anaconda2/envs/pytorch-mgn/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 49, in reset_parameters
    stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by levyfan** [comment]
make sure you have correctly download and unpack the dataset, and try debug by yourself
