### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCTensorRandom.cu:25

### ISSUE THREAD

**Issue by xxx2974** [levyfan/reid-mgn#9]
I also met the issue:
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCTensorRandom.cu:25

the details:
(pytorch-mgn) [xxx@localhost mgn]$ python mgn.py
cuda

Namespace(model='mgn', root='/home/xiaozhenzhen/data/reid-mgn/mgn/dataset/Market-1501-v15.09.15', workers=28.0)

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
Traceback (most recent call last):
  File "mgn.py", line 314, in <module>
    run()
  File "mgn.py", line 258, in run
    mgn = MGN(num_classes=len(train_dataset.unique_ids)).to(DEVICE)
  File "/home/xiaozhenzhen/anaconda2/envs/pytorch-mgn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 393, in to
    return self._apply(lambda t: t.to(device))
  File "/home/xiaozhenzhen/anaconda2/envs/pytorch-mgn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/home/xiaozhenzhen/anaconda2/envs/pytorch-mgn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/home/xiaozhenzhen/anaconda2/envs/pytorch-mgn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/home/xiaozhenzhen/anaconda2/envs/pytorch-mgn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 393, in <lambda>
    return self._apply(lambda t: t.to(device))
  File "/home/xiaozhenzhen/anaconda2/envs/pytorch-mgn/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCTensorRandom.cu:25

**Comment by levyfan** [comment]
out of memory, make sure you have enough gpu memory, or make batch size smaller
